os:
  - linux
  - osx
language: node_js
node_js:
  - 12
notifications:
  email: false
env:
  matrix:
    - PACKAGE=packages/parser
    - PACKAGE=packages/deparser
script:
  - yarn
  - yarn bootstrap
  - yarn build
  - cd $PACKAGE
  - yarn test
