os:
  - linux
  - osx
language: node_js
node_js:
  - 12
notifications:
  email: false
env:
  matrix:
    - PACKAGE=packages/parser
    - PACKAGE=packages/deparser
script:
  - yarn
  - yarn bootstrap
  - yarn build
  - cd $PACKAGE
  - yarn test

before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:deadsnakes/ppa; fi;
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi;
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python3.6; fi;
