os:
  - linux
  - osx
language: node_js
node_js:
  - 12
notifications:
  email: false
env:
  matrix:
    - PACKAGE=packages/parser
    - PACKAGE=packages/deparser
script:
  - yarn
  - yarn bootstrap
  - yarn build
  - cd $PACKAGE
  - yarn test

before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then pyenv install 3.6.3; fi;
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then pyenv global 3.6.3; fi;
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install pip --upgrade; fi;
